### ISSUE TITLE
Cursor positions are not adjusted once lines are added / removed to a file

### ISSUE THREAD

**Issue by dlikhten** [last-cursor-position/last-cursor-position#27]
I would expect this behavior: 

If a line was added / removed from a file, the position of every cursor after that line should be adjusted accordingly (++ / --).

**Comment by fcharron** [comment]
It would be much better to do this, indeed, but I don't have much time to work on this, which is why I'm looking for maintainers for the project. I'll try to come up with something. Thanks for the suggestion!

**Comment by wylie39** [comment]
See #42
