### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by wylie39** [last-cursor-position/last-cursor-position#40]
Could I be added as an admin to the repository So I can set tags and actions?

**Comment by fcharron** [comment]
I'm at work now, but sure, I'll look into it tonight!

--
François Charron

**Comment by fcharron** [comment]
Sent you an invite to a new Github organization. I'm working on transferring the repo to that organization, so I can give you admin access. Simple personal repos can only add "Collaborators", but as you've already figured out, it's pretty limited.

**Comment by fcharron** [comment]
Transfer is done, you're an admin. Just give me some time to update the atom repo with the updated URL before starting to push commits.

**Comment by wylie39** [comment]
Sounds good, when I add something how do I push It to atom?

**Comment by fcharron** [comment]
https://flight-manual.atom.io/hacking-atom/sections/publishing/ has the info about publishing. In short, once atom is installed, you can use `apm publish <version_type>` to publish. This will take care of pushing to Github, bump the version number according to the <version_type> (which can be "major", "minor", or "patch"), create a tag, and publishing to the atom repo.

**Comment by fcharron** [comment]
I've had trouble pushing to the repo just now (needed to mess around with my git config to make atom use ssh instead of https, which was causing problems on my machine), so I suggest you try and follow the steps in the link I provided, and let me know if you run into problems.

**Comment by wylie39** [comment]
It worked, Thanks so much for letting me help with this.

**Comment by fcharron** [comment]
Glad it worked, and I should thank you for helping out 🙂

--
François Charron
